### ISSUE TITLE
Fix // 3D `temp` failed on new workflow, while it was successful for 2D

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [Thomas-Moore-Creative/Climatology-generator-demo#10]
`composited_stats_BRAN2020.sh` & `composited_stats_BRAN2020.py` worked for 2D `eta_t` but the run for 3D `temp` failed and it's not clear from the output file `169K Apr 13 10:48 composited_stats_BRAN2020.sh.o113692670` why?

_NB: the output was very small_
```
-rw-r--r-- 1 tm4888 es60 133K Apr 13 10:24 BRAN2020_clim_demo_temp.nc
```

**Comment by Thomas-Moore-Creative** [comment]
next step: refactor ARE code using the [`flox.xarray.xarray_reduce`](https://flox.readthedocs.io/en/latest/generated/flox.xarray.xarray_reduce.html#flox.xarray.xarray_reduce) [Aggregations](https://flox.readthedocs.io/en/latest/aggregations.html) as in [these docs](https://flox.readthedocs.io/en/latest/intro.html)

- re-run on 2D `mld` and compare

**Comment by Thomas-Moore-Creative** [comment]
next step: rewrite the ARE code without `flox`, re-run on 2D `mld` and compare

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-04-18 at 13 34 12@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/a0b80e93-291c-4e09-95de-dacbfcb338be)

![CleanShot 2024-04-18 at 14 23 10@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/cd98552c-1178-4f0b-adda-7ae219590e27)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-04-19 at 09 45 25@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/5f6f3949-e1f9-4cfa-9a31-29d2c6847210)

![CleanShot 2024-04-19 at 09 45 40@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/474ad18c-8a65-45b5-aaf9-17802f8b0d8d)

**Comment by Thomas-Moore-Creative** [comment]
Reference: [Strategies for climatology calculations](https://flox.readthedocs.io/en/latest/user-stories/climatology.html)

> But what if we didn’t want to rechunk the dataset so drastically?

![CleanShot 2024-04-22 at 12 39 17@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/811aef6b-e751-4d47-80c0-342d472f05d8)

![CleanShot 2024-04-22 at 12 40 50@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/ce7afa10-eba2-4ab4-9c33-bc67795b310d)

![CleanShot 2024-04-22 at 12 44 39@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/ca608bf2-6ee5-48d7-b52e-9fb432dea8e4)

**Comment by Thomas-Moore-Creative** [comment]
but this chunking approach only works for:

- `mean`
- `std`
- `max`
- `min`

**Comment by dcherian** [comment]
LIke here for example. If you have monthly mean output and you're creating a monthly climatology and the chunk size is 1 along time then `method="cohorts"` should work beautifully, no rechunking/tuning required. Also flox *should* just choose it automatically.

> but this chunking approach only works for:

What other reductions are you looking for? `quantile` / `median`?

**Comment by Thomas-Moore-Creative** [comment]
closing this . . .
