### ISSUE TITLE
confirm (??) and fix zarr collection precision ( float32 vs float64 )

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [Thomas-Moore-Creative/Climatology-generator-demo#13]
confirm and fix zarr collection precision ( `float32` vs `float64` )
![CleanShot 2024-04-19 at 10 29 45@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/092c4f6e-b1f7-412c-b91c-8cb5a680c02f)
for 

`/scratch/es60/ard/reanalysis/BRAN2020/ARD/BRAN2020-daily-temp-v14032024.zarr`

**Comment by Thomas-Moore-Creative** [comment]
OK, part of the problem is that I developed my code (mostly) on the 2D variables and it turns out the BRAN2020 netcdf files:
- have different chunking for the 2D and 3D raw `nc` files (this is likely not the issue here)
- have different variable types for the 2D ( `float32`) vs 3D variables (`short`)

When the initial dataset object is loaded using `xarray` via paths provided by the `intake` catalog it reports to the screen UI that, for example, 3D `temp`, is `float32`.  But for some reason when this dataset is written to `zarr` the type is actually `float64`, blowing up the problem silently. I've confirmed that the 2D data reports `float32` to the screen UI but also writes `float32` into the corresponding `zarr` collection.

**So something about the `short` variable being lazy loaded vs computed is giving different precision?**

![CleanShot 2024-04-25 at 12 23 41@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/054c34cd-30af-4c4c-945c-04620130b54a)

```
ds.to_zarr(BRAN2020_ard_path+ard_file_ID,consolidated=True)
BRAN2020_daily_temp = xr.open_zarr(BRAN2020_ard_path+ard_file_ID,consolidated=True)
```
![CleanShot 2024-04-25 at 12 22 49@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/9f41aa70-900e-4bc3-870d-16b1b16cd092)



. . . . @ChrisC28 this is exactly the kind of ARD lessons it takes time to hack through (at least for me)

**Comment by Thomas-Moore-Creative** [comment]
for now, without a clear way to set the `short` variable compute to be a `float32` result I'm forcing `float32` via:
`DS[var]=DS[var].astype('float32')` which after testing seems to work delivering `float32` 3D variables in the `zarr` collection

**Comment by dsroberts** [comment]
Hi @Thomas-Moore-Creative, apropos of your comment on the Hive, here is a gist that loads `int16` data into Xarray directly then manually performs the `float32` conversion. Give it a go with your data and see if it helps:
https://gist.github.com/dsroberts/9b1e4e290b46663394e3f3f31292dc12

**Comment by Thomas-Moore-Creative** [comment]
issue resolved
