### ISSUE TITLE
install extra dependencies for numbagg

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [Thomas-Moore-Creative/Climatology-generator-demo#15]
### test `numbagg` for speeding up nan-skipping aggregations

https://github.com/xarray-contrib/flox/issues/346

**Comment by dcherian** [comment]
You'll see a slowdown due to compilation but then much faster aggregations, so bit of a tradeoff at the moment. Good for big problems IMO, less good for small problems so be careful with your test problem

**Comment by Thomas-Moore-Creative** [comment]
- [x] install `numbagg` into project environment
- [ ] ~~control use of `numbagg` via - `with xr.set_options(use_numbagg=False)`:~~

[https://pypi.org/project/numbagg/](https://pypi.org/project/numbagg/)

![CleanShot 2024-05-03 at 09 37 15@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/fc1f0e18-fd9c-412c-9531-a36d5689a89b)

**Comment by Thomas-Moore-Creative** [comment]
### first order findings

- Do you **have `NaN`'s** in your timeseries: > try `.groupby('time.month').mean('time',engine='numbagg').compute()`
- If the cluster fails use `flox` ( which should use `cohorts`method) > try `.groupby('time.month').mean('time',engine='flox',method='cohorts').compute()`
- If you **don't have `NaN`'s** in your timeseries: > try `.groupby('time.month').mean('time',engine='flox',method='cohorts',skipna=False).compute()`

**Comment by dcherian** [comment]
Re: your crashes: one possibility is https://github.com/numbagg/numbagg/issues/209

to get the full benefit of `numbagg`'s parallelism you'll need to install extra dependencies with pip, or install from conda.

**Comment by Thomas-Moore-Creative** [comment]
> Re: your crashes: one possibility is [numbagg/numbagg#209](https://github.com/numbagg/numbagg/issues/209)
> 
> to get the full benefit of `numbagg`'s parallelism you'll need to install extra dependencies with pip, or install from conda.

Thanks for pointing out this nitty-gritty detail! I installed numbagg via conda-forge but didn't seem to get those libraries? 

```
history | grep 'numbagg'
  836  mamba install numbagg -c conda-forge
```
but neither`llvm-openmp` or `tbb` appear in the conda list?

```
mamba list | grep 'tbb'
>
mamba list | grep 'llvm-openmp'
>
```

**Comment by dcherian** [comment]
Are you on windows? I remember some OS dependence here.

**Comment by Thomas-Moore-Creative** [comment]
project frozen
