### ISSUE TITLE
Final Report // Deliver products and draft content

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [Thomas-Moore-Creative/Climatology-generator-demo#4]
Converting the prototype code run on ARE ( Gadi Broadwell Nodes ) to batch (Gadi Cascade Lake nodes) has proven non-trivial.  I'm going to finish delivery of #2 using only ARE.

### next steps 

- [ ] sanity check all files after these last 3D runs
- [x] re-make 2D `zarr` collections
- [x] re-run all files for 2D `eta_t` & `mld` to ensure `12-2023` finish
- [x] backup results `netcdf`
- [x] combine results & address matt's comments on `netcdf` files
- [ ] check all metadata, make required edits, compression settings, chunking
- [ ] make diagram(s) of workflow
- [x] document the final netcdf results files
- [x] finish draft report

**Comment by Thomas-Moore-Creative** [comment]
@matt-csiro : here is where you can / will be able to get access to the `netcdf` output

#### location for draft `netcdf` product output

`/g/data/es60/users/thomas_moore/clim_demo_results/daily/draft_delivery/`

these will be complete in terms of data but may require metadata improvements & file name clarification

#### location for final `netcdf` product output

`/g/data/es60/users/thomas_moore/delivery/clim_stat_demo/`

files here will be final in terms of both completeness and improved metadata and/or file names

**Comment by Thomas-Moore-Creative** [comment]
@matt-csiro :

current draft `netcdf` files are:

```
/g/data/es60/users/thomas_moore/clim_demo_results/daily/draft_delivery ls -ltrh
total 74G
-rw-r--r-- 1 tm4888 es60  44G Apr  3 10:57 BRAN2020_daily_temperature_climatology.nc
-rw-r--r-- 1 tm4888 es60  13G Apr  3 10:58 BRAN2020_daily_temperature_quant.nc
-rw-r--r-- 1 tm4888 es60  16G Apr  3 10:59 BRAN2020_daily_temperature_stats.nc
-rw-r--r-- 1 tm4888 es60 742M Apr  3 11:07 BRAN2020_daily_eta_t_climatology.nc
-rw-r--r-- 1 tm4888 es60 310M Apr  3 11:07 BRAN2020_daily_eta_t_stats.nc
-rw-r--r-- 1 tm4888 es60 248M Apr  3 11:07 BRAN2020_daily_eta_t_quant.nc
-rw-r--r-- 1 tm4888 es60 248M Apr  3 11:07 BRAN2020_daily_mld_quant.nc
-rw-r--r-- 1 tm4888 es60 742M Apr  3 11:07 BRAN2020_daily_mld_climatology.nc
-rw-r--r-- 1 tm4888 es60 310M Apr  3 11:07 BRAN2020_daily_mld_stats.nc
```

**Comment by Thomas-Moore-Creative** [comment]
### progress on the remaining 3D variables 

- [x] Salinity
- [x] U
- [x] V

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-04-04 at 08 23 35@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/4a677c19-4ac1-41eb-a63e-7ae514fba0ed)
whoops, issue 4 not 3

**Comment by matt-csiro** [comment]
Noting here that we discussed, offline, generating all the statistics (mean, median, minimum, maximum, 5th percentile, 95th percentile and standard deviation) as monthly climatologies.

**Comment by Thomas-Moore-Creative** [comment]
@matt-csiro - `/g/data/es60/users/thomas_moore/clim_demo_results/daily/draft_delivery` is now empty pending refactoring how I do the output.

the older output files are still here:
`/g/data/es60/users/thomas_moore/clim_demo_results/daily/03042024_draft_delivery/`

**Comment by Thomas-Moore-Creative** [comment]
With the new climatology calculation workflow:

- 2D results from `chunked4time` zarr collections take about 20 minutes
- 3D results using ARE and single node hugemem (28cpu/1TB) are underway

**Comment by Thomas-Moore-Creative** [comment]
## sanity check on results
![CleanShot 2024-04-08 at 14 17 42@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/4fa06bf0-630d-4304-a721-1846b83dc97b)

![CleanShot 2024-04-08 at 14 17 59@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/9ac28a51-d354-442b-a057-27ee4aa76a2b)

![CleanShot 2024-04-08 at 14 30 16@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/dfbbf9d2-ae7f-465f-bf6f-4e753b64259c)

**Comment by Thomas-Moore-Creative** [comment]
### next steps

- [x] is `BRAN2020-daily-temp-chunk4time-v07022024.zarr` OK?
- [x] add ENSO compositing to workflow and run on 2D

**Comment by Thomas-Moore-Creative** [comment]
@matt-csiro 

As far as file structure how does this look to you?  I've not yet checked or added metadata.

`/g/data/es60/users/thomas_moore/clim_demo_results/daily/draft_delivery/BRAN2020_clim_demo_mld.nc`

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-04-10 at 16 11 13@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/9e5f5c61-2544-4229-89cf-101800f3fe94)

**Comment by matt-csiro** [comment]
> @matt-csiro
> 
> As far as file structure how does this look to you? I've not yet checked or added metadata.
> 
> `/g/data/es60/users/thomas_moore/clim_demo_results/daily/draft_delivery/BRAN2020_clim_demo_mld.nc`

The file structure looks like it is coming along.  
As discussed, there are a couple of considerations that would also bring down the file size.  
- There is no need for quantiles to be kept as doubles, at least convert to floats, or even consider packing to shorts like is done with the BRAN output.  
However, packing can get messy if different files have different scales and offsets, so staying with floats may be preferred (?)
- And also, turning on some deflation with netCDF4 which may reduce the file size by about half again.  For reference, BRAN output is just deflation level 1 and chunked (300,300,1,1) in (x,y,z,t), for variables with depth; seems to work well and didn't worry about optimising further.  

Adding some metadata to the time axis will be useful; please include a modulo attribute.

**Comment by matt-csiro** [comment]
Please check the quantiles for the el_nino and la_nina for eta and mld; in the versions in draft/ they are currently the same as all_years. 
For example, in the attached with eta el_nino profiles at y=0 and month=12, the quantiles (short dashes) in some places exceeds the min or max ('dots')
![eta2](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/42162322/2d31b791-892d-46bc-b7aa-1618d8226de5)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-04-11 at 08 10 32](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/40546b85-724c-49f1-9452-fc0a970fb677)
Gosh darn!  Yep, looks like `np.quant` doesn't work on `NaN` masked `xarray` objects like the other stats calculations. =(

Thanks heaps for picking that up @matt-csiro.  More eyes are good.

**Comment by Thomas-Moore-Creative** [comment]
> Please check the quantiles for the el_nino and la_nina for eta and mld; in the versions in draft/ they are currently the same as all_years. For example, in the attached with eta el_nino profiles at y=0 and month=12, the quantiles (short dashes) in some places exceeds the min or max ('dots') ![eta2](https://private-user-images.githubusercontent.com/42162322/321252783-2d31b791-892d-46bc-b7aa-1618d8226de5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDk4NjUsIm5iZiI6MTcxMjgwOTU2NSwicGF0aCI6Ii80MjE2MjMyMi8zMjEyNTI3ODMtMmQzMWI3OTEtODkyZC00NmJjLWI3YWEtMTYxOGQ4MjI2ZGU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA0MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGEzNWFlNDhjNzU5ZTE0ZTkzODE1MjI3MTY5ZjhlNjA1Mjg2MTBlMjUyZmY0M2U0ZTIzNWEzN2U3NzY5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDK0B-3oCL7_W_49-R8n_0qnZ0ssCggUBOb-9OIcEPo) [ ![eta2](https://private-user-images.githubusercontent.com/42162322/321252783-2d31b791-892d-46bc-b7aa-1618d8226de5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDk4NjUsIm5iZiI6MTcxMjgwOTU2NSwicGF0aCI6Ii80MjE2MjMyMi8zMjEyNTI3ODMtMmQzMWI3OTEtODkyZC00NmJjLWI3YWEtMTYxOGQ4MjI2ZGU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA0MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGEzNWFlNDhjNzU5ZTE0ZTkzODE1MjI3MTY5ZjhlNjA1Mjg2MTBlMjUyZmY0M2U0ZTIzNWEzN2U3NzY5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDK0B-3oCL7_W_49-R8n_0qnZ0ssCggUBOb-9OIcEPo) ](https://private-user-images.githubusercontent.com/42162322/321252783-2d31b791-892d-46bc-b7aa-1618d8226de5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDk4NjUsIm5iZiI6MTcxMjgwOTU2NSwicGF0aCI6Ii80MjE2MjMyMi8zMjEyNTI3ODMtMmQzMWI3OTEtODkyZC00NmJjLWI3YWEtMTYxOGQ4MjI2ZGU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA0MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGEzNWFlNDhjNzU5ZTE0ZTkzODE1MjI3MTY5ZjhlNjA1Mjg2MTBlMjUyZmY0M2U0ZTIzNWEzN2U3NzY5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDK0B-3oCL7_W_49-R8n_0qnZ0ssCggUBOb-9OIcEPo) [ ](https://private-user-images.githubusercontent.com/42162322/321252783-2d31b791-892d-46bc-b7aa-1618d8226de5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDk4NjUsIm5iZiI6MTcxMjgwOTU2NSwicGF0aCI6Ii80MjE2MjMyMi8zMjEyNTI3ODMtMmQzMWI3OTEtODkyZC00NmJjLWI3YWEtMTYxOGQ4MjI2ZGU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA0MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGEzNWFlNDhjNzU5ZTE0ZTkzODE1MjI3MTY5ZjhlNjA1Mjg2MTBlMjUyZmY0M2U0ZTIzNWEzN2U3NzY5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDK0B-3oCL7_W_49-R8n_0qnZ0ssCggUBOb-9OIcEPo)

@matt-csiro - this was a hard to see but very basic typo! fixed.

**Comment by Thomas-Moore-Creative** [comment]
sanity checking the new output #8

**Comment by Thomas-Moore-Creative** [comment]
@matt-csiro - the no-composite "all-time" job for all the stats (base + quant) is running well for 3D variables in about 7 hours.  As I refactor the ENSO-phases composites code I'm running the "all-time" results to make best use of the time.  Will bring them all back together in final `netcdf`'s.  

### "all-time" base stats and quant stats for `temp`
```
(base) tm4888@gadi-login-08 /g/data/es60/users/thomas_moore/clim_demo_results/daily/draft_delivery ls -ltrh *temp*
-rw-r--r-- 1 tm4888 es60 18G May 18 04:42 BRAN2020_base_stats_temp_alltime_2024.05.18.00.05.08.nc
-rw-r--r-- 1 tm4888 es60 11G May 18 07:35 BRAN2020_quantile_stats_temp_alltime_2024.05.18.00.05.08.nc
```

![CleanShot 2024-05-18 at 09 32 26@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/75adc8d4-0876-44a7-a606-71664d903852)

NB: there are clear differences between `median` and `mean`
![CleanShot 2024-05-18 at 09 48 30@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/edde951a-ca95-4708-b79a-93ed540638f1)

**Comment by Thomas-Moore-Creative** [comment]
# let's sanity check the `temp` in `Neutral phase` 
![CleanShot 2024-05-19 at 14 44 12](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/731b1c64-8e84-4424-b07f-5044830fad20)

**Comment by Thomas-Moore-Creative** [comment]
### sanity check `temp` `all-time` minus `neutral`
![CleanShot 2024-05-19 at 15 00 03](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/5198bfa0-06c2-4089-9255-a2272828339b)

**Comment by Thomas-Moore-Creative** [comment]
### sanity check `all-time` `salt`
![CleanShot 2024-05-19 at 15 20 14](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/8f62e216-7493-45f0-b196-a876601e8690)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-05-19 at 15 24 53](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/f5b471b7-0197-46da-bfdc-c1a0f3e6addc)

@matt-csiro - ~~I should probably better understand the eastern pacific, and there are many rivers and embayments on the South American coastline but are we expecting this range of `salt` at the coast near the equator?~~
**Ummmm... yeah, that's the Atlantic (duh! I need an eye exam)** **It's that river called the _Amazon_.**
![CleanShot 2024-05-19 at 17 35 38](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/3a753988-b312-4c90-b03c-5a6d07ee154e)
![CleanShot 2024-05-19 at 17 37 37](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/2a46afb5-6247-4568-925b-d365571f642e)
![CleanShot 2024-05-19 at 18 09 49](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/147e1a03-648e-424e-8fec-f80b506af3be)


![SSS_SouthAM_eq - 01](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/f0200597-0684-4d37-be3f-6a1ca736665d)

**Comment by Thomas-Moore-Creative** [comment]
![CleanShot 2024-05-30 at 16 05 47@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/fbd92635-6184-49b2-ba3a-079dcee2a12f)
need a better approach to plot all 28 stats & phases for each variable . . .

... a broken y axis can help using [https://github.com/bendichter/brokenaxes](https://github.com/bendichter/brokenaxes)

![Unknown](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/1d7e8c04-1a39-4b5f-8f9f-37fd47fee94a)

**Comment by Thomas-Moore-Creative** [comment]
### after conversion to GISready files
![CleanShot 2024-06-13 at 14 26 32@2x](https://github.com/Thomas-Moore-Creative/Climatology-generator-demo/assets/36463906/9e0d8a10-9fd7-45cd-a937-47a6e5cb397b)

**Comment by Thomas-Moore-Creative** [comment]
report finished
